spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: 123456

##mybatis-plus配置
#mybatis-plus:
#  mapper-locations: classpath*:/mapper/**/*.xml